
name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          registry-url: "https://npm.pkg.github.com"
      
      - name: Check Node and npm verision
        run: | 
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Create .npmrc
        run: |
          echo "@MdTaslimuddinAnsari:registry=https://npm.pkg.github.com" > build/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NPM_TOKEN}" >> build/.npmrc

      - name: Publish package
        working-directory: ./build
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
